language: python
python:
  - "3.7"
install:
  - pip install -e .
  - pip install -e .[travis]
script:
  - pycodestyle clashroyaleapi
  - pylint clashroyaleapi --rcfile=.pylintrc
  - mypy clashroyaleapi